name: todo_list
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.1
  path: 1.9.0

  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Rajdhani
      fonts:
       - asset: fonts/Rajdhani-Regular.ttf 
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
